package main

import "fmt"

func printHelp() {
	fmt.Println("iloscript 1.2.0 - HPE iLO Redfish command line client")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  iloscript <ilo_ip> <command> [arguments]")
	fmt.Println()
	fmt.Println("Authentication:")
	fmt.Println("  ILO_USERNAME and ILO_PASSWORD environment variables are used when set.")
	fmt.Println("  Otherwise the legacy default account Administrator/compaq is used.")
	fmt.Println()
	fmt.Println("System and inventory commands:")
	fmt.Println("  -model                              Show the system model.")
	fmt.Println("  -pca                                Show PCA serial and iLO ASIC information.")
	fmt.Println("  -ver                                List firmware inventory.")
	fmt.Println("  -devices                            List PCI devices.")
	fmt.Println("  -sensors                            List chassis sensor readings.")
	fmt.Println("  -iel                                Show server EventLog entries.")
	fmt.Println()
	fmt.Println("IML commands:")
	fmt.Println("  -iml [count] [text] [severity]       Fetch IML entries once.")
	fmt.Println("  -iml monitor [count] [text] [severity]")
	fmt.Println("                                      Refresh IML every 5 seconds.")
	fmt.Println("  severity                             Critical, Warning, or OK.")
	fmt.Println()
	fmt.Println("Power commands:")
	fmt.Println("  -power on                            Power on using advertised Redfish action.")
	fmt.Println("  -power off                           Power off using advertised Redfish action.")
	fmt.Println("  -power reset                         Cold boot/restart using capability detection.")
	fmt.Println("  -power status                        Print the current PowerState.")
	fmt.Println("  -power monitor                       Refresh PowerState every 5 seconds.")
	fmt.Println()
	fmt.Println("Firmware commands:")
	fmt.Println("  -firmware <image_path> [text]        Upload a local image using Redfish capabilities.")
	fmt.Println("  <firmware_url> [text]                Ask iLO to fetch a remote image.")
	fmt.Println("                                      Both forms monitor the returned task.")
	fmt.Println()
	fmt.Println("BIOS and maintenance commands:")
	fmt.Println("  -bios get                            Show BIOS attributes.")
	fmt.Println("  -bios setup                          Boot into BIOS setup.")
	fmt.Println("  -bios reset                          Restore BIOS defaults and power on.")
	fmt.Println("  -bios patch <attribute> <value>      Change one BIOS attribute.")
	fmt.Println("  -reset                               Clear logs and reset iLO.")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  iloscript 192.0.2.10 -iml 20 SATA Critical")
	fmt.Println("  iloscript 192.0.2.10 -iml monitor 10 SATA")
	fmt.Println("  iloscript 192.0.2.10 -power monitor")
	fmt.Println("  iloscript 192.0.2.10 -firmware ./ilo7.fwpkg")
}
