package main

import "fmt"

func printHelp() {
	fmt.Println("iloscript 1.2.0 - HPE iLO Redfish command line client")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  iloscript <ilo_ip> <command> [arguments]")
	fmt.Println()
	fmt.Println("Authentication:")
	fmt.Println("  ILO_USERNAME and ILO_PASSWORD environment variables are used when set.")
	fmt.Println("  Otherwise the legacy default account Administrator/compaq is used.")
	fmt.Println("  -v, --verbose                       Print safe HTTP/task diagnostics to stderr.")
	fmt.Println()
	fmt.Println("System and inventory commands:")
	fmt.Println("  -model                              Show the system model.")
	fmt.Println("  -pca                                Show PCA serial and iLO ASIC information.")
	fmt.Println("  -ver                                List firmware inventory.")
	fmt.Println("  -devices                            Hardware report: firmware, storage, CPU, memory, NIC, power supply.")
	fmt.Println("  -storage                            List storage drives sorted by Port, Box, and Bay.")
	fmt.Println("  -storage --bay                      Sort storage drives by Box, then Bay.")
	fmt.Println("  -storage --led                      Light each drive location indicator for 20 seconds.")
	fmt.Println("  -storage --bay --led                Use Box/Bay order for the LED sequence.")
	fmt.Println("  -sensors                            List chassis sensor readings.")
	fmt.Println("  -iel                                Show server EventLog entries.")
	fmt.Println("  -iel --clear                        Clear only the IEL entries.")
	fmt.Println()
	fmt.Println("IML commands:")
	fmt.Println("  -iml [count] [text] [severity]       Fetch IML entries once.")
	fmt.Println("  -iml --clear                         Clear only the IML entries.")
	fmt.Println("  -iml monitor [count] [text] [severity]")
	fmt.Println("                                      Refresh IML every 5 seconds.")
	fmt.Println("  severity                             Critical, Warning, or OK.")
	fmt.Println()
	fmt.Println("Power commands:")
	fmt.Println("  -power on                            Power on using advertised Redfish action.")
	fmt.Println("  -power off                           Power off using advertised Redfish action.")
	fmt.Println("  -power reset                         Cold boot/restart using capability detection.")
	fmt.Println("  -power status                        Print the current PowerState.")
	fmt.Println("  -power monitor                       Refresh PowerState every 5 seconds.")
	fmt.Println()
	fmt.Println("Firmware commands:")
	fmt.Println("  -firmware <image_path> [text] [--target auto|bios|ilo|manual]")
	fmt.Println("                                      Upload a local image using Redfish capabilities.")
	fmt.Println("  <firmware_url> [text] [--target auto|bios|ilo|manual]")
	fmt.Println("                                      Ask iLO to fetch a remote image.")
	fmt.Println("  auto                                Let iLO determine the firmware target and monitor status.")
	fmt.Println("  bios                                Discover the updateable System ROM target.")
	fmt.Println("  ilo                                 Discover the updateable iLO/BMC target.")
	fmt.Println("  manual                              List inventory ID, Name, Version, Description and select an ID.")
	fmt.Println("                                      The selected inventory @odata.id is sent to iLO.")
	fmt.Println("  (default)                           Use bios when --target is omitted.")
	fmt.Println()
	fmt.Println("BIOS and maintenance commands:")
	fmt.Println("  -bios get                            Show BIOS attributes.")
	fmt.Println("  -bios setup                          Boot into BIOS setup.")
	fmt.Println("  -bios reset                          Restore BIOS defaults and power on.")
	fmt.Println("  -bios patch <attribute> <value>      Change one BIOS attribute.")
	fmt.Println("  -reset                               Clear logs and reset iLO.")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  iloscript 192.0.2.10 -iml 20 SATA Critical")
	fmt.Println("  iloscript 192.0.2.10 -iml monitor 10 SATA")
	fmt.Println("  iloscript 192.0.2.10 -power monitor")
	fmt.Println("  iloscript 192.0.2.10 -firmware ./A72_1.10.signed.full --target bios")
	fmt.Println("  iloscript 192.0.2.10 https://192.0.2.20/A72_1.10.signed.full --target bios")
	fmt.Println()
	fmt.Println("Firmware safety:")
	fmt.Println("  The client reads UpdateService/FirmwareInventory for bios, ilo, and manual targets.")
	fmt.Println("  It sends the discovered @odata.id and verifies that target version after completion.")
	fmt.Println("  auto omits Targets and relies on iLO; it monitors task/update status only.")
	fmt.Println("  HTTP 200 alone is never treated as a completed firmware update.")
}
